import esbuild from "esbuild";
import process from "process";
import builtinModules from "builtin-modules";

const isProduction = process.argv[2] === 'production';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

let baseOptions = {
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: isProduction ? false : 'inline',
	treeShaking: true,
	jsx: 'automatic',
	outfile: 'main.js',
};

let buildOptions = {
	...baseOptions,
	plugins: [
		{
			name: 'watch-plugin',
			setup(build) {
				build.onEnd(() => {
					console.log('Build finished');
				});
			},
		},
	],
};

if (isProduction) {
	buildOptions = {
		...baseOptions,
		minify: true,
	};
}

esbuild.build(buildOptions).catch(() => process.exit(1));

